### ISSUE TITLE
Issue getting on method to work on my div

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/TicTacToeGame#1]
Userstory:
As a player clicks a box on the grid, 
I want to be able to show an X or O based on the player,
so I can keep track of who is doing what in the game.

Test statement :
On click a div, X appears if player one and O appears if player two.

context/text:
My simply alert isn't working when I use the on method on one of my div under class name box. 

$(".box").on( "click", function() {
        alert('works');
});

**Comment by amadden80** [comment]
Once you fill in the issue, we will respond asap.  Thanks

**Comment by eerlikh** [comment]
I solved the issue with onclick on my html. Let me know if that is ok solution and why on didn't work.

**Comment by amadden80** [comment]
Ok.  Great.  I will look now.  Please add, commit, push your work.
I can't see your code without you doing that.

We normally want to stay away from inline click events.  Push it up and I'll take a look.

**Comment by eerlikh** [comment]
one sec

**Comment by eerlikh** [comment]
Ok, I pushed the files I have to github

**Comment by eerlikh** [comment]
My new issue is currently figuring out the toggle method. Should I start a new issue for my toggle problem?

**Comment by amadden80** [comment]
I'll close this issue after I take a peak.  You should open a new issue with all the required details for your next issue after working through it on your own for some time.

**Comment by eerlikh** [comment]
Yeah, I never really solved this issue, I just changed my method

**Comment by amadden80** [comment]
Regarding your original Issue, we do not like to see inline javascript, like the `onclick`

Rather than that, you should return to the `.on('click'` method.

I believe you had a load order issue.  Could I be right?

The below code should work as long as the DOM is ready.
You could consider moving it into a document ready function.

``` js
$( ".box" ).on('click', function() {
  alert('yay')
});
```

Does that resolve this issue?

**Comment by eerlikh** [comment]
yes sir, thank you

**Comment by amadden80** [comment]
Great!   When an issue has been resolved for you, please close the issue by clicking the close button below.  That way we know the issue no longer needs attention.  Thanks
