### ISSUE TITLE
Problems alternating turns between players in JS

### ISSUE THREAD

**Issue by eerlikh** [eerlikh/TicTacToeGame#3]
ok ok ok

So during my meeting with Andrew I was shown a lot of cool stuff and it was a lot to take in. 
## user story working on -

As a player clicks a box on the grid,
I want to be able to show an X or O based on the player,
so I can keep track of who is doing what in the game.
## Test Statement -

clicking on the grid should show and X or an O
## Context - here is a jsfiddle for full

http://jsfiddle.net/cu37kLtr/

when i’m trying to do this thing -

```
// if(currentTurn%2==0){
//        playerOneLogic()
//        currentTurn++;
//    } else if(currentTurn%2==1){
//      alert('two '+ currentTurn)
//        playerTwoLogic()
//        currentTurn++;
//    }
```

The problem is player 2 is always skipped!!!!
I tried changing the conditions for the conditional statement and made sure all my css and html and everything makes sense ><

Also, Andrew's code works but it's a bit confusing as I have never used the data method yet. I'd need further explanation to manipulate this code snippet successfully. 

 $('.box').on('click', function(){
      currentTurn++;
      $(this).data('player', players[ currentTurn%2 ]); // Save data with the node
      $(this).addClass('P-' + players[ currentTurn%2 ]);

For example please explain why blue overwrites red but red can't overwrite blue. why does this function work the way it does??? I need to figure this alternating issue before I proceed to my final step, victory conditions.

i have tried….
what triggers the bug..

**Comment by eerlikh** [comment]
I think I solved it

**Comment by eerlikh** [comment]
Basically
the conditional statement isn't exiting the player logic function

**Comment by eerlikh** [comment]
issue resolved!

**Comment by emilylordahl** [comment]
Nice job Eduard!
